f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div class="hero">\n')
w('  <div class="hbadge">&#127891; Student Visual Guide</div>\n')
w('  <h1>John Locke Institute<br><span>Economics Essay 2026</span></h1>\n')
w('  <p>Your complete visual companion &mdash; questions, arguments, essay structure, and winning strategy.</p>\n')
w('  <div class="cg">\n')
w('    <div class="ci"><span class="num" id="d1">18</span><span class="lbl">Days to Questions</span></div>\n')
w('    <div class="ci"><span class="num" id="d2">57</span><span class="lbl">Days to Secondary</span></div>\n')
w('    <div class="ci"><span class="num" id="d3">78</span><span class="lbl">Days to Deadline</span></div>\n')
w('    <div class="ci"><span class="num">~2,000</span><span class="lbl">Word Limit</span></div>\n')
w('  </div>\n</div>\n')
w('<div class="nav-tabs">\n')
w('  <div class="nav-tab active" onclick="show(\'overview\')">&#127919; Overview</div>\n')
w('  <div class="nav-tab" onclick="show(\'q1\')">&#128178; Q1: Cashless</div>\n')
w('  <div class="nav-tab" onclick="show(\'q2\')">&#128200; Q2: Pricing</div>\n')
w('  <div class="nav-tab" onclick="show(\'q3\')">&#128188; Q3: Bezos</div>\n')
w('  <div class="nav-tab" onclick="show(\'timeline\')">&#128197; Timeline</div>\n')
w('  <div class="nav-tab" onclick="show(\'scoring\')">&#127942; Scoring</div>\n')
w('  <div class="nav-tab" onclick="show(\'resources\')">&#128218; Resources</div>\n')
w('  <div class="nav-tab" onclick="show(\'mentorship\')">&#127891; Mentorship</div>\n')
w('  <div class="nav-tab" onclick="show(\'pastq\')">&#128203; Past Questions</div>\n')
w('  <div class="nav-tab" onclick="show(\'deepdive\')">&#128300; Deep Dive</div>\n')
w('  <div class="nav-tab" onclick="show(\'econres\')">&#128202; Econ Research</div>\n')
w('</div>\n')
f.close()
print("Part 2 done")