f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="q1" class="section">\n')
w('<div class="stitle" style="color:var(--q1)">&#128178; Q1: Should we fear a cashless society?</div>\n')
w('<div class="ssub">Monetary Economics &bull; Privacy &bull; Financial Inclusion</div>\n')
w('<div style="background:linear-gradient(135deg,#0369a1,#0891b2);border-radius:14px;padding:22px;margin-bottom:18px;color:#fff">\n')
w('<h2 style="font-size:20px;margin-bottom:10px">Should we fear a cashless society?</h2>\n')
w('<div style="font-size:12px;opacity:.85;font-family:Arial,sans-serif">Key terms: <span style="background:rgba(255,255,255,.2);padding:2px 7px;border-radius:10px;margin-right:5px">cashless society</span><span style="background:rgba(255,255,255,.2);padding:2px 7px;border-radius:10px;margin-right:5px">fear</span><span style="background:rgba(255,255,255,.2);padding:2px 7px;border-radius:10px">monetary freedom</span></div>\n')
w('</div>\n')
w('<div class="sh">&#9876; The Core Debate</div>\n')
w('<div class="dg">\n')
w('<div class="ds rs"><div class="dh r">&#128308; YES &mdash; We Should Fear It</div>\n')
w('<div class="dp"><div><strong>&#128065; Surveillance capitalism</strong><em>Every transaction tracked; governments gain total financial visibility</em></div></div>\n')
w('<div class="dp"><div><strong>&#128683; Financial exclusion</strong><em>1.4B unbanked globally (World Bank 2021); elderly, rural, low-income excluded</em></div></div>\n')
w('<div class="dp"><div><strong>&#9889; System fragility</strong><em>Power outages, cyberattacks leave people unable to transact</em></div></div>\n')
w('<div class="dp"><div><strong>&#128274; Loss of monetary freedom</strong><em>Negative rates, spending controls, account freezes become trivially easy</em></div></div>\n')
w('</div>\n')
w('<div class="ds gs"><div class="dh g">&#128994; NO &mdash; Benefits Outweigh Fears</div>\n')
w('<div class="dp"><div><strong>&#128176; Efficiency gains</strong><em>Eliminates cash handling costs (~0.5% GDP); faster settlement</em></div></div>\n')
w('<div class="dp"><div><strong>&#128373; Reduces crime</strong><em>Tax evasion, money laundering rely on cash anonymity</em></div></div>\n')
w('<div class="dp"><div><strong>&#128200; Financial inclusion</strong><em>M-Pesa brought banking to 96% of Kenyan households</em></div></div>\n')
w('<div class="dp"><div><strong>&#128202; Transparency</strong><em>Reduces corruption; audit trails improve public accountability</em></div></div>\n')
w('</div>\n</div>\n')
w('<div class="sh">&#128203; Key Data</div>\n')
w('<div class="datagrid">\n')
w('<div class="dc"><div class="dstat">98%</div><div class="ddesc">Sweden transactions are digital (2023)</div><div class="dsrc">Riksbank</div></div>\n')
w('<div class="dc"><div class="dstat">1.4B</div><div class="ddesc">Adults globally without bank accounts</div><div class="dsrc">World Bank 2021</div></div>\n')
w('<div class="dc"><div class="dstat">130+</div><div class="ddesc">Countries exploring CBDCs</div><div class="dsrc">Atlantic Council 2024</div></div>\n')
w('<div class="dc"><div class="dstat">0.5%</div><div class="ddesc">GDP cost of cash handling in advanced economies</div><div class="dsrc">ECB</div></div>\n')
w('</div>\n')
w('<div class="sh">&#128221; Sample Thesis Statements</div>\n')
w('<div class="tg">\n')
w('<div class="tc"><div class="tl">Strong YES Thesis</div><div class="tt">A cashless society should be feared not because digital payments are inherently dangerous, but because the infrastructure required creates unprecedented tools for financial surveillance and exclusion that no democratic safeguard has yet proven adequate to constrain.</div></div>\n')
w('<div class="tc"><div class="tl">Strong NO Thesis</div><div class="tt">The fears surrounding a cashless society, while not unfounded, are outweighed by the concrete benefits of financial inclusion, reduced crime, and monetary policy effectiveness &mdash; provided robust regulatory frameworks accompany the transition.</div></div>\n')
w('<div class="tc"><div class="tl">Nuanced Thesis</div><div class="tt">Whether we should fear a cashless society depends entirely on the institutional context: in liberal democracies with strong data protection, the benefits dominate; in authoritarian states, the same technology becomes an instrument of control.</div></div>\n')
w('</div>\n')
w('<div class="sh">&#128196; Essay Structure (5 paragraphs)</div>\n')
w('<div class="sf">\n')
w('<div class="ss"><div class="sn" style="background:#2563eb;color:#fff">1</div><div class="sb"><div class="stit">Introduction <span class="spct" style="background:#dbeafe;color:#1d4ed8">~200 words</span></div><div class="spts">Define cashless society. Acknowledge the trend (Sweden, China). State your thesis clearly. Preview your argument structure.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#0891b2;color:#fff">2</div><div class="sb"><div class="stit">The Case FOR Fear <span class="spct" style="background:#e0f2fe;color:#0369a1">~400 words</span></div><div class="spts">Privacy/surveillance (strongest argument). Financial exclusion of vulnerable groups. System fragility and geopolitical risk.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#059669;color:#fff">3</div><div class="sb"><div class="stit">The Case AGAINST Fear <span class="spct" style="background:#d1fae5;color:#065f46">~400 words</span></div><div class="spts">Efficiency and inclusion benefits. Crime reduction. Monetary policy tools. Counter the exclusion argument with M-Pesa evidence.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#7c3aed;color:#fff">4</div><div class="sb"><div class="stit">Critical Analysis <span class="spct" style="background:#ede9fe;color:#5b21b6">~400 words</span></div><div class="spts">The institutional context matters most. Distinguish between cashless by choice vs. by mandate. Role of regulation and GDPR-style protections.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#f59e0b;color:#fff">5</div><div class="sb"><div class="stit">Conclusion <span class="spct" style="background:#fef3c7;color:#92400e">~200 words</span></div><div class="spts">Restate thesis with nuance. Acknowledge strongest counterargument. End with a forward-looking insight about institutional design.</div></div></div>\n')
w('</div>\n</div>\n')
f.close()
print("Part 4 done")