f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="q2" class="section">\n')
w('<div class="stitle" style="color:var(--q2)">&#128200; Q2: Personalised Pricing Effects</div>\n')
w('<div class="ssub">Behavioural Economics &bull; Price Discrimination &bull; Welfare Analysis</div>\n')
w('<div style="background:linear-gradient(135deg,#5b21b6,#7c3aed);border-radius:14px;padding:22px;margin-bottom:18px;color:#fff">\n')
w('<h2 style="font-size:20px;margin-bottom:10px">Technology now allows personalised pricing. If this came to be widely used, what effects should we expect?</h2>\n')
w('<div style="font-size:12px;opacity:.85;font-family:Arial,sans-serif">Key terms: <span style="background:rgba(255,255,255,.2);padding:2px 7px;border-radius:10px;margin-right:5px">personalised pricing</span><span style="background:rgba(255,255,255,.2);padding:2px 7px;border-radius:10px;margin-right:5px">welfare effects</span><span style="background:rgba(255,255,255,.2);padding:2px 7px;border-radius:10px">market power</span></div>\n')
w('</div>\n')
w('<div class="sh">&#128202; Effects Framework</div>\n')
w('<div class="dg">\n')
w('<div class="ds rs"><div class="dh r">&#128308; Negative Effects</div>\n')
w('<div class="dp"><div><strong>&#128100; Consumer surplus extraction</strong><em>Firms capture ALL consumer surplus; buyers pay their exact willingness-to-pay</em></div></div>\n')
w('<div class="dp"><div><strong>&#128065; Privacy erosion</strong><em>Requires mass data collection; normalises surveillance of purchasing behaviour</em></div></div>\n')
w('<div class="dp"><div><strong>&#9878; Fairness concerns</strong><em>Poor pay more relative to income; discrimination by race/gender possible</em></div></div>\n')
w('<div class="dp"><div><strong>&#127963; Market power entrenchment</strong><em>Data-rich incumbents gain permanent advantage; barriers to entry rise</em></div></div>\n')
w('</div>\n')
w('<div class="ds gs"><div class="dh g">&#128994; Positive Effects</div>\n')
w('<div class="dp"><div><strong>&#128200; Allocative efficiency</strong><em>Perfect price discrimination = perfectly competitive output; no deadweight loss</em></div></div>\n')
w('<div class="dp"><div><strong>&#128176; Access expansion</strong><em>Low-income consumers can access goods at lower prices (airlines, software)</em></div></div>\n')
w('<div class="dp"><div><strong>&#127775; Innovation incentives</strong><em>Higher profits fund R&amp;D; pharmaceutical pricing enables drug development</em></div></div>\n')
w('<div class="dp"><div><strong>&#128203; Better matching</strong><em>Prices signal true valuations; resources allocated to highest-value uses</em></div></div>\n')
w('</div>\n</div>\n')
w('<div class="sh">&#128221; Sample Thesis Statements</div>\n')
w('<div class="tg">\n')
w('<div class="tc"><div class="tl">Efficiency Focus</div><div class="tt">Widespread personalised pricing would improve allocative efficiency and expand access to goods for low-income consumers, but only if accompanied by strong anti-discrimination regulation to prevent the technology from entrenching existing inequalities.</div></div>\n')
w('<div class="tc"><div class="tl">Fairness Focus</div><div class="tt">The widespread adoption of personalised pricing would represent a fundamental shift in market power from consumers to firms, extracting consumer surplus at scale while creating new forms of discrimination that existing competition law is ill-equipped to address.</div></div>\n')
w('</div>\n')
w('<div class="sh">&#128196; Essay Structure</div>\n')
w('<div class="sf">\n')
w('<div class="ss"><div class="sn" style="background:#7c3aed;color:#fff">1</div><div class="sb"><div class="stit">Introduction</div><div class="spts">Define personalised pricing (3rd degree price discrimination at scale). Give examples: Uber surge, Amazon dynamic pricing, airline tickets.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#7c3aed;color:#fff">2</div><div class="sb"><div class="stit">Efficiency Effects</div><div class="spts">Welfare analysis: deadweight loss elimination vs. consumer surplus transfer. Use supply/demand diagram logic. Distinguish 1st, 2nd, 3rd degree discrimination.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#7c3aed;color:#fff">3</div><div class="sb"><div class="stit">Distributional Effects</div><div class="spts">Who wins and who loses? Firms gain, consumers lose surplus. But low-WTP consumers may gain access. Equity implications.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#7c3aed;color:#fff">4</div><div class="sb"><div class="stit">Market Structure Effects</div><div class="spts">Data as competitive moat. Network effects. Regulatory response needed. GDPR, algorithmic transparency.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#7c3aed;color:#fff">5</div><div class="sb"><div class="stit">Conclusion</div><div class="spts">Net assessment: efficiency gains real but distributional concerns dominate without regulation. Policy recommendations.</div></div></div>\n')
w('</div>\n</div>\n')
f.close()
print("Part 5 done")