f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="resources" class="section">\n')
w('<div class="stitle">&#128218; Essential Reading &amp; Resources</div>\n')
w('<div class="ssub">Curated reading list for all three questions</div>\n')
w('<div class="sh">&#128218; Core Economics Books</div>\n')
w('<div class="readgrid">\n')
w('<div class="bk"><div class="bki" style="background:#dbeafe">&#128218;</div><div><div class="bkt">The Wealth of Nations</div><div class="bka">Adam Smith &mdash; Foundation text</div><span class="bktag" style="background:#dbeafe;color:#1d4ed8">All Questions</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#ede9fe">&#128218;</div><div><div class="bkt">Thinking, Fast and Slow</div><div class="bka">Daniel Kahneman &mdash; Behavioural economics</div><span class="bktag" style="background:#ede9fe;color:#5b21b6">Q2 Pricing</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#d1fae5">&#128218;</div><div><div class="bkt">The Everything Store</div><div class="bka">Brad Stone &mdash; Amazon biography</div><span class="bktag" style="background:#d1fae5;color:#065f46">Q3 Bezos</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#e0f2fe">&#128218;</div><div><div class="bkt">The Age of Surveillance Capitalism</div><div class="bka">Shoshana Zuboff</div><span class="bktag" style="background:#e0f2fe;color:#0369a1">Q1 Cashless</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#fef3c7">&#128218;</div><div><div class="bkt">Capital in the 21st Century</div><div class="bka">Thomas Piketty &mdash; Inequality</div><span class="bktag" style="background:#fef3c7;color:#92400e">Q3 Bezos</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#fee2e2">&#128218;</div><div><div class="bkt">The Price of Everything</div><div class="bka">Eduardo Porter &mdash; Pricing economics</div><span class="bktag" style="background:#fee2e2;color:#991b1b">Q2 Pricing</span></div></div>\n')
w('</div>\n')
w('<div class="sh">&#127760; Key Data Sources</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn" style="background:var(--q1)">Q1</div><div><div class="tipt">Cashless Society Sources</div><div class="tipd">Riksbank (Sweden data) &bull; World Bank Financial Inclusion Database &bull; Atlantic Council CBDC Tracker &bull; ECB cash usage reports &bull; BIS working papers on digital currency</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:var(--q2)">Q2</div><div><div class="tipt">Personalised Pricing Sources</div><div class="tipd">OECD reports on algorithmic pricing &bull; Competition &amp; Markets Authority (UK) reports &bull; Varian (1989) "Price Discrimination" &bull; Pigou\'s Economics of Welfare &bull; FTC reports on data brokers</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:var(--q3)">Q3</div><div><div class="tipt">Amazon / Bezos Sources</div><div class="tipd">Strategic Organising Centre injury reports &bull; Amazon annual reports &bull; BLS occupational injury data &bull; Lina Khan "Amazon\'s Antitrust Paradox" (Yale Law Journal) &bull; Forbes wealth data</div></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128161; Writing Tips from Past Winners</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn">A</div><div><div class="tipt">Start with a hook, not a definition</div><div class="tipd">Open with a striking fact or paradox. "In 2023, Sweden\'s central bank warned that going cashless too fast could threaten financial stability" is better than "A cashless society is one where..."</div></div></div>\n')
w('<div class="tip"><div class="tipn">B</div><div><div class="tipt">Use the Toulmin structure</div><div class="tipd">Claim &rarr; Grounds (evidence) &rarr; Warrant (why evidence supports claim) &rarr; Qualifier (limits) &rarr; Rebuttal (counterargument). This is the gold standard for analytical essays.</div></div></div>\n')
w('<div class="tip"><div class="tipn">C</div><div><div class="tipt">End paragraphs with analysis, not summary</div><div class="tipd">The last sentence of each body paragraph should advance your argument, not just summarise what you said. Ask: "So what does this mean for my thesis?"</div></div></div>\n')
w('<div class="tip"><div class="tipn">D</div><div><div class="tipt">Cite economists by name</div><div class="tipd">Naming Pigou, Varian, or Tirole signals you have read the literature. It also gives your argument authority beyond just your own reasoning.</div></div></div>\n')
w('</div>\n</div>\n')
f.close()
print("Part 9 done")