f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="q3" class="section">\n')
w('<div class="stitle" style="color:var(--q3)">&#128188; Q3: Did Bezos Get Rich at Others\' Expense?</div>\n')
w('<div class="ssub">Labour Economics &bull; Wealth Creation &bull; Consumer Surplus &bull; Inequality</div>\n')
w('<div style="background:linear-gradient(135deg,#065f46,#059669);border-radius:14px;padding:22px;margin-bottom:18px;color:#fff">\n')
w('<h2 style="font-size:20px;margin-bottom:10px">Did Jeff Bezos get rich at the expense of his customers, his employees, neither or both?</h2>\n')
w('<div style="font-size:12px;opacity:.85;font-family:Arial,sans-serif">Key terms: <span style="background:rgba(255,255,255,.2);padding:2px 7px;border-radius:10px;margin-right:5px">at the expense of</span><span style="background:rgba(255,255,255,.2);padding:2px 7px;border-radius:10px;margin-right:5px">customers</span><span style="background:rgba(255,255,255,.2);padding:2px 7px;border-radius:10px">employees</span></div>\n')
w('</div>\n')
w('<div class="alert info"><span>&#128161;</span><div><strong>Key analytical move:</strong> "At the expense of" means zero-sum &mdash; one party gains ONLY because another loses. You must test whether each relationship is zero-sum or positive-sum.</div></div>\n')
w('<div class="sh">&#128100; The Four Possible Answers</div>\n')
w('<div class="sg" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr))">\n')
w('<div class="sc" style="border-top:4px solid var(--red)"><div class="si">&#128308;</div><div class="sv" style="color:var(--red)">Both</div><div class="sl">Customers AND employees exploited</div></div>\n')
w('<div class="sc" style="border-top:4px solid var(--q1)"><div class="si">&#128309;</div><div class="sv" style="color:var(--q1)">Customers Only</div><div class="sl">Monopoly pricing, but workers fine</div></div>\n')
w('<div class="sc" style="border-top:4px solid var(--gold)"><div class="si">&#128992;</div><div class="sv" style="color:var(--gold)">Employees Only</div><div class="sl">Customers benefit, workers exploited</div></div>\n')
w('<div class="sc" style="border-top:4px solid var(--green)"><div class="si">&#128994;</div><div class="sv" style="color:var(--green)">Neither</div><div class="sl">Positive-sum wealth creation</div></div>\n')
w('</div>\n')
w('<div class="sh">&#128202; The Evidence</div>\n')
w('<div class="dg">\n')
w('<div class="ds gs"><div class="dh g">&#128994; NOT at Customers\' Expense</div>\n')
w('<div class="dp"><div><strong>&#128200; Consumer surplus massive</strong><em>Amazon Prime saves avg. household $1,000+/yr; prices consistently below rivals</em></div></div>\n')
w('<div class="dp"><div><strong>&#128176; Competitive pricing</strong><em>Amazon built market share through LOW prices, not monopoly extraction</em></div></div>\n')
w('<div class="dp"><div><strong>&#127775; Innovation value</strong><em>AWS, Prime Video, Alexa &mdash; new products customers value highly</em></div></div>\n')
w('</div>\n')
w('<div class="ds rs"><div class="dh r">&#128308; YES at Employees\' Expense</div>\n')
w('<div class="dp"><div><strong>&#128683; Warehouse conditions</strong><em>Injury rates 2x industry average (Strategic Organising Centre 2021)</em></div></div>\n')
w('<div class="dp"><div><strong>&#128100; Monopsony power</strong><em>Amazon = 45% of US e-commerce; dominant employer in many regions</em></div></div>\n')
w('<div class="dp"><div><strong>&#128274; Anti-union practices</strong><em>Documented union-busting; workers lack bargaining power to capture value created</em></div></div>\n')
w('<div class="dp"><div><strong>&#128202; Wage suppression</strong><em>Median Amazon wage below living wage in many markets until $15 minimum (2018)</em></div></div>\n')
w('</div>\n</div>\n')
w('<div class="sh">&#128203; Key Data</div>\n')
w('<div class="datagrid">\n')
w('<div class="dc"><div class="dstat">$177B</div><div class="ddesc">Bezos peak net worth (2021)</div><div class="dsrc">Forbes</div></div>\n')
w('<div class="dc"><div class="dstat">1.5M</div><div class="ddesc">Amazon employees globally (2023)</div><div class="dsrc">Amazon</div></div>\n')
w('<div class="dc"><div class="dstat">2x</div><div class="ddesc">Amazon warehouse injury rate vs. industry average</div><div class="dsrc">SOC 2021</div></div>\n')
w('<div class="dc"><div class="dstat">$1,000+</div><div class="ddesc">Annual consumer surplus per Prime household</div><div class="dsrc">Estimates</div></div>\n')
w('</div>\n')
w('<div class="sh">&#128221; Sample Thesis Statements</div>\n')
w('<div class="tg">\n')
w('<div class="tc"><div class="tl">Employees Yes, Customers No</div><div class="tt">Bezos did not get rich at the expense of his customers &mdash; Amazon created enormous consumer surplus through competitive pricing and innovation. However, the evidence strongly suggests that Amazon\'s warehouse workers bore disproportionate costs through suppressed wages, unsafe conditions, and systematic denial of bargaining power.</div></div>\n')
w('<div class="tc"><div class="tl">Neither (Positive-Sum)</div><div class="tt">Bezos\'s wealth reflects genuine value creation: Amazon transformed retail efficiency, created millions of jobs, and delivered unprecedented consumer value. The question\'s zero-sum framing misunderstands how entrepreneurial wealth is generated in competitive markets.</div></div>\n')
w('</div>\n')
w('<div class="sh">&#128196; Essay Structure</div>\n')
w('<div class="sf">\n')
w('<div class="ss"><div class="sn" style="background:#059669;color:#fff">1</div><div class="sb"><div class="stit">Introduction</div><div class="spts">Define "at the expense of" as zero-sum. Introduce Amazon\'s scale. State your answer clearly upfront.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#059669;color:#fff">2</div><div class="sb"><div class="stit">Customers: Positive-Sum</div><div class="spts">Consumer surplus evidence. Competitive pricing strategy. Network effects and innovation. Verdict: NOT at customers\' expense.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#059669;color:#fff">3</div><div class="sb"><div class="stit">Employees: Mixed Evidence</div><div class="spts">Wage data and injury rates. Monopsony power analysis. $15 minimum wage counterargument. Verdict: Partially at employees\' expense.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#059669;color:#fff">4</div><div class="sb"><div class="stit">Structural Analysis</div><div class="spts">Is this about Bezos specifically or capitalism generally? Role of regulation. Could workers have captured more value?</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#059669;color:#fff">5</div><div class="sb"><div class="stit">Conclusion</div><div class="spts">Bezos got rich primarily through value creation (not extraction from customers), but workers did bear real costs. The answer is: employees yes, customers no.</div></div></div>\n')
w('</div>\n</div>\n')
f.close()
print("Part 6 done")