f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="pastq" class="section">\n')
w('<div class="stitle">&#128203; Past Questions Analysis (2019&ndash;2024)</div>\n')
w('<div class="ssub">Pattern recognition &mdash; what JLI asks, what they reward, and how 2026 fits the mould</div>\n')
w('<div class="sh">&#128197; Questions by Year</div>\n')
w('<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px;margin-bottom:18px">\n')
w('<div class="card"><div class="ctitle">2024</div><div class="al"><li>Is it possible to be too rich?</li><li>Should we worry about the national debt?</li><li>Is free trade always beneficial?</li></div></div>\n')
w('<div class="card"><div class="ctitle">2023</div><div class="al"><li>Should we tax the rich more?</li><li>Is economic growth always desirable?</li><li>Should we worry about automation?</li></div></div>\n')
w('<div class="card"><div class="ctitle">2022</div><div class="al"><li>Is capitalism the best economic system?</li><li>Should we have a universal basic income?</li><li>Is globalisation good for the poor?</li></div></div>\n')
w('<div class="card"><div class="ctitle">2021</div><div class="al"><li>Should we worry about inequality?</li><li>Is there a case for protectionism?</li><li>Should we tax carbon?</li></div></div>\n')
w('<div class="card"><div class="ctitle">2020</div><div class="al"><li>Is economic growth compatible with environmental sustainability?</li><li>Should we worry about the power of big tech?</li><li>Is there a case for a minimum wage?</li></div></div>\n')
w('<div class="card"><div class="ctitle">2019</div><div class="al"><li>Should we worry about the national debt?</li><li>Is free trade always beneficial?</li><li>Should we tax the rich more?</li></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128202; Question Type Breakdown</div>\n')
w('<div class="sg" style="grid-template-columns:repeat(auto-fit,minmax(180px,1fr))">\n')
w('<div class="sc" style="border-top:4px solid var(--q1)"><div class="si">&#128308;</div><div class="sv" style="color:var(--q1)">60%</div><div class="sl">Normative "Should we..." (most common)</div></div>\n')
w('<div class="sc" style="border-top:4px solid var(--q2)"><div class="si">&#128309;</div><div class="sv" style="color:var(--q2)">25%</div><div class="sl">Evaluative "Is X always/best..."</div></div>\n')
w('<div class="sc" style="border-top:4px solid var(--q3)"><div class="si">&#128992;</div><div class="sv" style="color:var(--q3)">15%</div><div class="sl">Causal/Analytical "Is X compatible with..."</div></div>\n')
w('</div>\n')
w('<div class="sh">&#128200; Recurring Themes &amp; 2026 Relevance</div>\n')
w('<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:13px;font-family:Arial,sans-serif">\n')
w('<tr style="background:#1e293b;color:#fff"><th style="padding:10px;text-align:left">Theme</th><th style="padding:10px">Years Appeared</th><th style="padding:10px">2026 Relevance</th><th style="padding:10px;text-align:left">Linked Question</th></tr>\n')
w('<tr style="background:#f8fafc"><td style="padding:9px;font-weight:600">Inequality &amp; redistribution</td><td style="padding:9px;text-align:center">2019, 2021, 2023, 2024</td><td style="padding:9px;text-align:center"><span style="background:#d1fae5;color:#065f46;padding:2px 8px;border-radius:10px;font-size:11px">HIGH</span></td><td style="padding:9px">Q3 Bezos</td></tr>\n')
w('<tr><td style="padding:9px;font-weight:600">Technology &amp; economy</td><td style="padding:9px;text-align:center">2020, 2023</td><td style="padding:9px;text-align:center"><span style="background:#d1fae5;color:#065f46;padding:2px 8px;border-radius:10px;font-size:11px">HIGH</span></td><td style="padding:9px">Q1, Q2</td></tr>\n')
w('<tr style="background:#f8fafc"><td style="padding:9px;font-weight:600">Market systems</td><td style="padding:9px;text-align:center">2020, 2022</td><td style="padding:9px;text-align:center"><span style="background:#fef3c7;color:#92400e;padding:2px 8px;border-radius:10px;font-size:11px">MEDIUM</span></td><td style="padding:9px">Q2</td></tr>\n')
w('<tr><td style="padding:9px;font-weight:600">Trade &amp; globalisation</td><td style="padding:9px;text-align:center">2019, 2021, 2022</td><td style="padding:9px;text-align:center"><span style="background:#fef3c7;color:#92400e;padding:2px 8px;border-radius:10px;font-size:11px">MEDIUM</span></td><td style="padding:9px">Background context</td></tr>\n')
w('<tr style="background:#f8fafc"><td style="padding:9px;font-weight:600">Debt &amp; fiscal policy</td><td style="padding:9px;text-align:center">2019, 2024</td><td style="padding:9px;text-align:center"><span style="background:#fee2e2;color:#991b1b;padding:2px 8px;border-radius:10px;font-size:11px">LOW</span></td><td style="padding:9px">Not in 2026</td></tr>\n')
w('</table></div>\n')
f.close()
print("Part 13 done")