f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div class="sh">&#128197; Essay Writing Strategy (4 Phases)</div>\n')
w('<div class="sf">\n')
w('<div class="ss"><div class="sn" style="background:#2563eb;color:#fff">1</div><div class="sb"><div class="stit">Topic Selection (Week 1-2)</div><div class="spts">Wait for official 2026 questions (April 1). Evaluate each question against your interests and knowledge. Choose where you can offer the most original perspective.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#7c3aed;color:#fff">2</div><div class="sb"><div class="stit">Research Deep Dive (Week 2-4)</div><div class="spts">Read foundational academic papers. Gather current data and statistics. Identify 2-3 case studies. Map out counterarguments before writing.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#059669;color:#fff">3</div><div class="sb"><div class="stit">Outline &amp; Draft (Week 4-6)</div><div class="spts">Create detailed outline with thesis statement. Write first draft focusing on argument flow. Ensure each paragraph advances the argument &mdash; no filler.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#d97706;color:#fff">4</div><div class="sb"><div class="stit">Revision &amp; Polish (Week 6-8)</div><div class="spts">Get feedback from mentors/teachers. Strengthen weak arguments. Refine prose and eliminate redundancy. Final proofread before submission.</div></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128218; Recommended Reading List</div>\n')
w('<div class="readgrid">\n')
w('<div class="bk"><div class="bki" style="background:#dbeafe">&#128218;</div><div><div class="bkt">Good Economics for Hard Times</div><div class="bka">Banerjee &amp; Duflo &mdash; Policy debates</div><span class="bktag" style="background:#dbeafe;color:#1d4ed8">Contemporary</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#ede9fe">&#128218;</div><div><div class="bkt">Thinking, Fast and Slow</div><div class="bka">Daniel Kahneman &mdash; Behavioural economics</div><span class="bktag" style="background:#ede9fe;color:#5b21b6">Behavioural</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#d1fae5">&#128218;</div><div><div class="bkt">Capital in the 21st Century</div><div class="bka">Thomas Piketty &mdash; Inequality</div><span class="bktag" style="background:#d1fae5;color:#065f46">Inequality</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#fef3c7">&#128218;</div><div><div class="bkt">The Deficit Myth</div><div class="bka">Stephanie Kelton &mdash; Modern Monetary Theory</div><span class="bktag" style="background:#fef3c7;color:#92400e">Fiscal</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#fee2e2">&#128218;</div><div><div class="bkt">Narrative Economics</div><div class="bka">Robert Shiller &mdash; How stories drive economies</div><span class="bktag" style="background:#fee2e2;color:#991b1b">Theory</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#e0f2fe">&#128218;</div><div><div class="bkt">They Say / I Say</div><div class="bka">Graff &amp; Birkenstein &mdash; Academic argumentation</div><span class="bktag" style="background:#e0f2fe;color:#0369a1">Writing</span></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128101; Key Economists to Reference</div>\n')
w('<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:13px">\n')
w('<tr style="background:#1e293b;color:#fff"><th style="padding:9px;text-align:left">Economist</th><th style="padding:9px;text-align:left">Key Contribution</th><th style="padding:9px;text-align:left">Relevant For</th></tr>\n')
w('<tr style="background:#f8fafc"><td style="padding:9px;font-weight:600">Adam Smith</td><td style="padding:9px">Invisible hand, division of labour</td><td style="padding:9px">Market mechanisms</td></tr>\n')
w('<tr><td style="padding:9px;font-weight:600">John Maynard Keynes</td><td style="padding:9px">Aggregate demand, fiscal policy</td><td style="padding:9px">Government intervention</td></tr>\n')
w('<tr style="background:#f8fafc"><td style="padding:9px;font-weight:600">Milton Friedman</td><td style="padding:9px">Monetarism, free markets</td><td style="padding:9px">Monetary policy</td></tr>\n')
w('<tr><td style="padding:9px;font-weight:600">Amartya Sen</td><td style="padding:9px">Capabilities approach, welfare</td><td style="padding:9px">Development, inequality</td></tr>\n')
w('<tr style="background:#f8fafc"><td style="padding:9px;font-weight:600">Daron Acemoglu</td><td style="padding:9px">Institutions, technology &amp; growth</td><td style="padding:9px">AI economics, growth</td></tr>\n')
w('<tr><td style="padding:9px;font-weight:600">Esther Duflo</td><td style="padding:9px">RCTs in development economics</td><td style="padding:9px">Evidence-based policy</td></tr>\n')
w('</table></div>\n')
w('<div class="sh">&#127760; Key Data Sources</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn" style="background:#2563eb">1</div><div><div class="tipt"><a href="https://data.worldbank.org" target="_blank">World Bank Open Data</a></div><div class="tipd">Global development indicators &mdash; essential for cross-country comparisons and inequality data</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#dc2626">2</div><div><div class="tipt"><a href="https://fred.stlouisfed.org" target="_blank">FRED (Federal Reserve)</a></div><div class="tipd">US economic data &mdash; inflation, employment, GDP, monetary policy indicators</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#059669">3</div><div><div class="tipt"><a href="https://stats.oecd.org" target="_blank">OECD Statistics</a></div><div class="tipd">Comparative country data &mdash; tax rates, health spending, education, labour markets</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#d97706">4</div><div><div class="tipt"><a href="https://ourworldindata.org" target="_blank">Our World in Data</a></div><div class="tipd">Visualisations and datasets on global trends &mdash; excellent for finding striking statistics</div></div></div>\n')
w('</div>\n')
w('</div>\n')
f.close()
print("Part 19 done")