f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div class="footer">&#127891; John Locke Institute 2026 Economics Essay &mdash; Visual Guide &bull; Created for student preparation &bull; <a href="https://www.johnlockeinstitute.com" target="_blank">johnlockeinstitute.com</a></div>\n')
w('<script>\n')
w('function show(id) {\n')
w('  document.querySelectorAll(".section").forEach(s => s.classList.remove("active"));\n')
w('  document.querySelectorAll(".nav-tab").forEach(t => t.classList.remove("active"));\n')
w('  var el = document.getElementById(id);\n')
w('  if (el) el.classList.add("active");\n')
w('  var tabs = document.querySelectorAll(".nav-tab");\n')
w('  var map={overview:0,q1:1,q2:2,q3:3,timeline:4,scoring:5,resources:6,mentorship:7,pastq:8,deepdive:9,econres:10};\n')
w('  if (map[id] !== undefined && tabs[map[id]]) tabs[map[id]].classList.add("active");\n')
w('}\n')
w('(function() {\n')
w('  var deadlines = [\n')
w('    new Date("2026-04-01"),\n')
w('    new Date("2026-05-10"),\n')
w('    new Date("2026-05-31")\n')
w('  ];\n')
w('  var ids = ["d1","d2","d3"];\n')
w('  var now = new Date();\n')
w('  deadlines.forEach(function(d, i) {\n')
w('    var diff = Math.ceil((d - now) / 86400000);\n')
w('    var el = document.getElementById(ids[i]);\n')
w('    if (el) el.textContent = diff > 0 ? diff : "PASSED";\n')
w('  });\n')
w('})();\n')
w('</script>\n')
w('</body>\n</html>\n')
f.close()
print("Part 10 done")