f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="overview" class="section active">\n')
w('<div class="stitle">&#127919; Competition Overview</div>\n')
w('<div class="ssub">John Locke Institute Essay Competition 2026 &mdash; Economics Category</div>\n')
w('<div class="sg">\n')
w('<div class="sc"><div class="si">&#127942;</div><div class="sv">JLI 2026</div><div class="sl">Competition</div></div>\n')
w('<div class="sc"><div class="si">&#128197;</div><div class="sv">Apr 1</div><div class="sl">Questions Released</div></div>\n')
w('<div class="sc"><div class="si">&#128203;</div><div class="sv">May 10</div><div class="sl">Secondary Deadline</div></div>\n')
w('<div class="sc"><div class="si">&#127937;</div><div class="sv">May 31</div><div class="sl">Final Deadline</div></div>\n')
w('<div class="sc"><div class="si">&#128221;</div><div class="sv">~2,000</div><div class="sl">Word Limit</div></div>\n')
w('<div class="sc"><div class="si">&#128218;</div><div class="sv">3</div><div class="sl">Questions to Choose</div></div>\n')
w('</div>\n')
w('<div class="sh">&#127775; The 3 Official 2026 Questions</div>\n')
w('<div class="qs">\n')
w('<div class="qc q1" onclick="show(\'q1\')">\n')
w('<div class="qn">Question 1 &bull; Evaluation</div>\n')
w('<div class="qtag">&#128178; Monetary Economics</div>\n')
w('<h3>Should we fear a cashless society?</h3>\n')
w('<div class="qmeta">Privacy &bull; Financial Inclusion &bull; Monetary Freedom &bull; Surveillance</div>\n')
w('</div>\n')
w('<div class="qc q2" onclick="show(\'q2\')">\n')
w('<div class="qn">Question 2 &bull; Effects Analysis</div>\n')
w('<div class="qtag">&#128200; Behavioural Economics</div>\n')
w('<h3>Technology now allows personalised pricing. If this came to be widely used, what effects should we expect?</h3>\n')
w('<div class="qmeta">Price Discrimination &bull; Efficiency &bull; Fairness &bull; Market Power</div>\n')
w('</div>\n')
w('<div class="qc q3" onclick="show(\'q3\')">\n')
w('<div class="qn">Question 3 &bull; Distributional Analysis</div>\n')
w('<div class="qtag">&#128188; Labour Economics</div>\n')
w('<h3>Did Jeff Bezos get rich at the expense of his customers, his employees, neither or both?</h3>\n')
w('<div class="qmeta">Wealth Creation &bull; Labour &bull; Consumer Surplus &bull; Inequality</div>\n')
w('</div>\n</div>\n')
w('<div class="sh">&#9878; Cross-Cutting Themes</div>\n')
w('<div class="themegrid">\n')
w('<div class="thm"><div class="thmi">&#9889;</div><div class="thmt">Technology &amp; Power</div><div class="thmd">All three questions involve technology shifting power between groups</div><div class="thmq"><span class="thmqb q1">1</span><span class="thmqb q2">2</span><span class="thmqb q3">3</span></div></div>\n')
w('<div class="thm"><div class="thmi">&#9878;</div><div class="thmt">Efficiency vs. Fairness</div><div class="thmd">The classic economic trade-off appears in each question</div><div class="thmq"><span class="thmqb q1">1</span><span class="thmqb q2">2</span><span class="thmqb q3">3</span></div></div>\n')
w('<div class="thm"><div class="thmi">&#128100;</div><div class="thmt">Who Bears the Costs?</div><div class="thmd">Distributional analysis is central to all three questions</div><div class="thmq"><span class="thmqb q1">1</span><span class="thmqb q2">2</span><span class="thmqb q3">3</span></div></div>\n')
w('<div class="thm"><div class="thmi">&#127963;</div><div class="thmt">Role of Institutions</div><div class="thmd">Regulation, law, and policy shape outcomes in each case</div><div class="thmq"><span class="thmqb q1">1</span><span class="thmqb q2">2</span><span class="thmqb q3">3</span></div></div>\n')
w('<div class="thm"><div class="thmi">&#128065;</div><div class="thmt">Visibility of Harm</div><div class="thmd">Some costs are visible, others hidden (privacy loss, wage suppression)</div><div class="thmq"><span class="thmqb q1">1</span><span class="thmqb q2">2</span><span class="thmqb q3">3</span></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128202; Which Question to Choose?</div>\n')
w('<div class="card"><div class="ctitle">Quick Decision Guide</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn" style="background:var(--q1)">Q1</div><div><div class="tipt">Cashless Society</div><div class="tipd">Best if you are interested in monetary policy, privacy rights, or financial inclusion. Strong data available. Normative question allows clear thesis.</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:var(--q2)">Q2</div><div><div class="tipt">Personalised Pricing</div><div class="tipd">Best if you enjoy microeconomics and welfare analysis. Requires nuanced multi-stakeholder analysis. Cutting-edge topic with limited settled literature.</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:var(--q3)">Q3</div><div><div class="tipt">Bezos / Amazon</div><div class="tipd">Best if you like case studies and labour economics. Concrete data on Amazon. Risk of being descriptive rather than analytical &mdash; requires discipline.</div></div></div>\n')
w('</div></div>\n')
w('</div>\n')
f.close()
print("Part 3 done")