f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="timeline" class="section">\n')
w('<div class="stitle">&#128197; Preparation Timeline</div>\n')
w('<div class="ssub">From now to submission &mdash; a week-by-week action plan</div>\n')
w('<div class="timeline">\n')
w('<div class="ti"><div class="td2 p1"></div><div class="badge bb">NOW &mdash; Mar 14</div><div class="ttitle">Foundation Phase</div><div class="ttasks">Read all 3 question analyses in this guide. Choose your question. Read 2 core economics texts. Build your argument skeleton.</div></div>\n')
w('<div class="ti"><div class="td2 p1"></div><div class="badge bb">Mar 15&ndash;31</div><div class="ttitle">Deep Research Phase</div><div class="ttasks">Gather 8&ndash;10 academic sources. Find 5&ndash;6 compelling data points. Read opposing viewpoints. Draft your thesis statement.</div></div>\n')
w('<div class="ti"><div class="td2 ms"></div><div class="badge bg2">Apr 1</div><div class="ttitle">&#127937; Questions Released</div><div class="ttasks">Confirm your question choice. Adjust research if needed. Begin outline.</div></div>\n')
w('<div class="ti"><div class="td2 p2"></div><div class="badge bp">Apr 1&ndash;20</div><div class="ttitle">First Draft Phase</div><div class="ttasks">Write introduction and thesis. Draft body paragraphs. Don\'t self-edit yet &mdash; get ideas on paper. Aim for 2,500 words (will cut later).</div></div>\n')
w('<div class="ti"><div class="td2 p2"></div><div class="badge bp">Apr 21&ndash;30</div><div class="ttitle">Revision Phase</div><div class="ttasks">Cut to ~2,000 words. Strengthen thesis. Add specific evidence. Improve transitions. Get feedback from teacher/mentor.</div></div>\n')
w('<div class="ti"><div class="td2 p3"></div><div class="badge bgr">May 1&ndash;9</div><div class="ttitle">Polish Phase</div><div class="ttasks">Final argument check. Proofread for grammar. Verify all citations. Format bibliography. Read aloud for flow.</div></div>\n')
w('<div class="ti"><div class="td2 ms"></div><div class="badge bg2">May 10</div><div class="ttitle">&#128203; Secondary School Deadline</div><div class="ttasks">Submit if you are in secondary school category.</div></div>\n')
w('<div class="ti"><div class="td2 dl"></div><div class="badge br">May 31</div><div class="ttitle">&#128680; Final Deadline</div><div class="ttasks">All submissions due. Do not leave to last minute &mdash; submit by May 28 to allow for technical issues.</div></div>\n')
w('</div>\n')
w('<div class="sh">&#9989; Weekly Checklist</div>\n')
w('<div class="card"><div class="ctitle">Pre-Questions (Now &mdash; Apr 1)</div>\n')
w('<div class="al">\n')
w('<li><span>&#9744;</span><strong>Choose your question</strong> based on your strengths and interests</li>\n')
w('<li><span>&#9744;</span><strong>Read 2 economics books</strong> relevant to your question</li>\n')
w('<li><span>&#9744;</span><strong>Find 5 academic papers</strong> or credible sources</li>\n')
w('<li><span>&#9744;</span><strong>Draft 3 possible thesis statements</strong> and pick the strongest</li>\n')
w('<li><span>&#9744;</span><strong>Create an argument map</strong> showing your main points and evidence</li>\n')
w('<li><span>&#9744;</span><strong>Identify your strongest counterargument</strong> and prepare a response</li>\n')
w('</div></div>\n')
w('</div>\n')
f.close()
print("Part 7 done")