f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div class="sh">&#128202; Recommendation Matrix</div>\n')
w('<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:13px;font-family:Arial,sans-serif">\n')
w('<tr style="background:#1e293b;color:#fff"><th style="padding:10px;text-align:left">Organization</th><th style="padding:10px">Cost</th><th style="padding:10px">JLI Relevance</th><th style="padding:10px">Timeline</th><th style="padding:10px;text-align:left">Best For</th></tr>\n')
w('<tr style="background:#f8fafc"><td style="padding:9px;font-weight:600">Polygence</td><td style="padding:9px;text-align:center">$$$</td><td style="padding:9px;text-align:center">&#11088;&#11088;&#11088;&#11088;&#11088;</td><td style="padding:9px;text-align:center">4-6 wks</td><td style="padding:9px">1-on-1 economics mentorship</td></tr>\n')
w('<tr><td style="padding:9px;font-weight:600">Lumiere Education</td><td style="padding:9px;text-align:center">$$$</td><td style="padding:9px;text-align:center">&#11088;&#11088;&#11088;&#11088;&#11088;</td><td style="padding:9px;text-align:center">4-8 wks</td><td style="padding:9px">Research + essay coaching</td></tr>\n')
w('<tr style="background:#f8fafc"><td style="padding:9px;font-weight:600">John Locke Institute</td><td style="padding:9px;text-align:center">$$$</td><td style="padding:9px;text-align:center">&#11088;&#11088;&#11088;&#11088;&#11088;</td><td style="padding:9px;text-align:center">Now</td><td style="padding:9px">Direct competition prep</td></tr>\n')
w('<tr><td style="padding:9px;font-weight:600">Crimson Education</td><td style="padding:9px;text-align:center">$$$$</td><td style="padding:9px;text-align:center">&#11088;&#11088;&#11088;&#11088;</td><td style="padding:9px;text-align:center">2-4 wks</td><td style="padding:9px">Essay coaching</td></tr>\n')
w('<tr style="background:#f8fafc"><td style="padding:9px;font-weight:600">Young Economists Society</td><td style="padding:9px;text-align:center">$</td><td style="padding:9px;text-align:center">&#11088;&#11088;&#11088;&#11088;</td><td style="padding:9px;text-align:center">Flexible</td><td style="padding:9px">Economics community</td></tr>\n')
w('<tr><td style="padding:9px;font-weight:600">Marginal Revolution Uni</td><td style="padding:9px;text-align:center">Free</td><td style="padding:9px;text-align:center">&#11088;&#11088;&#11088;</td><td style="padding:9px;text-align:center">Immediate</td><td style="padding:9px">Economics knowledge</td></tr>\n')
w('<tr style="background:#f8fafc"><td style="padding:9px;font-weight:600">School Teacher</td><td style="padding:9px;text-align:center">Free</td><td style="padding:9px;text-align:center">&#11088;&#11088;&#11088;&#11088;</td><td style="padding:9px;text-align:center">Immediate</td><td style="padding:9px">Feedback and guidance</td></tr>\n')
w('</table></div>\n')
w('<div class="sh">&#9989; Immediate Action Plan</div>\n')
w('<div class="card"><div class="ctitle">This Week &mdash; Free Actions</div>\n')
w('<div class="al">\n')
w('<li><span>1</span><strong>Email your economics teacher</strong> &mdash; ask for mentorship and reading recommendations</li>\n')
w('<li><span>2</span><strong>Sign up for Marginal Revolution University</strong> &mdash; start economics courses today</li>\n')
w('<li><span>3</span><strong>Read past JLI winning essays</strong> &mdash; available on johnlockeinstitute.com</li>\n')
w('<li><span>4</span><strong>Subscribe to The Economist</strong> &mdash; student rate ~&pound;5/month</li>\n')
w('</div></div>\n')
w('<div class="card" style="margin-top:12px"><div class="ctitle">Within 2 Weeks</div>\n')
w('<div class="al">\n')
w('<li><span>5</span><strong>Contact Young Economists Society</strong> &mdash; join the community</li>\n')
w('<li><span>6</span><strong>Access NBER papers</strong> &mdash; find academic sources for your question</li>\n')
w('<li><span>7</span><strong>Email a university economics department</strong> &mdash; ask about student outreach</li>\n')
w('</div></div>\n')
w('<div class="sh">&#128683; Red Flags to Avoid</div>\n')
w('<div class="al">\n')
w('<li><span>&#10060;</span><strong>Organizations that write essays FOR students</strong> &mdash; academic dishonesty, disqualification risk</li>\n')
w('<li><span>&#10060;</span><strong>Programs that promise guaranteed wins</strong> &mdash; no legitimate program can guarantee this</li>\n')
w('<li><span>&#10060;</span><strong>Mentors without relevant academic credentials</strong> &mdash; check their economics background</li>\n')
w('<li><span>&#10060;</span><strong>Very short turnaround programs</strong> &mdash; good mentorship takes time; avoid last-minute fixes</li>\n')
w('</div>\n')
w('</div>\n')
f.close()
print("Part 12 done")