f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div class="sh">&#127775; 2026 Questions vs. Historical Patterns</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn" style="background:var(--q1)">Q1</div><div><div class="tipt">Cashless Society &mdash; Historical Parallel: "Should we worry about big tech?" (2020)</div><div class="tipd">Type: Normative "Should we..." (most common type &mdash; 60% of all questions). Advantage: clear normative framing makes thesis easy to construct. Key difference: more specific (cashless) vs. general (big tech).</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:var(--q2)">Q2</div><div><div class="tipt">Personalised Pricing &mdash; Historical Parallel: "Is globalisation good for the poor?" (2022)</div><div class="tipd">Type: Analytical/Effects (less common &mdash; 15%). Challenge: no normative framing makes thesis harder to construct. Risk of being descriptive. Requires multi-stakeholder welfare analysis.</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:var(--q3)">Q3</div><div><div class="tipt">Bezos &mdash; Historical Parallel: "Is it possible to be too rich?" (2024) + "Should we worry about inequality?" (2021)</div><div class="tipd">Type: Evaluative/Causal hybrid. Advantage: concrete Amazon data available; clear zero-sum analytical framework. Risk: being descriptive rather than analytical.</div></div></div>\n')
w('</div>\n')
w('<div class="sh">&#127775; Winning Strategies by Question Type</div>\n')
w('<div class="sf">\n')
w('<div class="ss"><div class="sn" style="background:#2563eb;color:#fff">1</div><div class="sb"><div class="stit">Policy Evaluation: "Should we [do X]?"</div><div class="spts">Don\'t give a simple yes/no. Best answers are conditional. Framework: "It depends on [conditions A, B, C]." Define the policy precisely, identify goals (efficiency/equity), evaluate against each, consider implementation, conclude with conditional recommendation.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#7c3aed;color:#fff">2</div><div class="sb"><div class="stit">Assumption Challenge: "Is X always/ever Y?"</div><div class="spts">Answer is almost always "no, not always." Find the exceptions. Identify conditions under which the assumption holds and fails. Conclude with a more nuanced principle than the question implies.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#059669;color:#fff">3</div><div class="sb"><div class="stit">Systemic/Conceptual: "Is X compatible with Y?"</div><div class="spts">Define both terms precisely. Distinguish between different versions of X and interpretations of Y. Argue for a specific version of X that could achieve Y. Acknowledge what would need to change.</div></div></div>\n')
w('<div class="ss"><div class="sn" style="background:#d97706;color:#fff">4</div><div class="sb"><div class="stit">Distributional: "Is X good for group Y?"</div><div class="spts">Disaggregate the group. "The poor" is not homogeneous. Distinguish absolute vs. relative gains. Use specific country/group data. Conclude with conditions under which X helps or harms.</div></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128202; The "It Depends" Framework</div>\n')
w('<div class="card"><div class="ctitle">For almost any economics question, the winning answer involves these 6 factors</div>\n')
w('<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:10px;margin-top:12px">\n')
w('<div style="background:#f1f5f9;border-radius:10px;padding:12px"><div style="font-weight:700;color:#1e293b;margin-bottom:4px">&#128337; Time Horizon</div><div style="font-size:12px;color:#64748b">Short-term vs. long-term effects? What looks bad now may be good later (and vice versa).</div></div>\n')
w('<div style="background:#f1f5f9;border-radius:10px;padding:12px"><div style="font-weight:700;color:#1e293b;margin-bottom:4px">&#128200; Scale</div><div style="font-size:12px;color:#64748b">Does it work at small scale but not large? Many policies fail when universalised.</div></div>\n')
w('<div style="background:#f1f5f9;border-radius:10px;padding:12px"><div style="font-weight:700;color:#1e293b;margin-bottom:4px">&#127963; Context</div><div style="font-size:12px;color:#64748b">Does it depend on institutions, culture, or history? What works in Sweden may not work in India.</div></div>\n')
w('<div style="background:#f1f5f9;border-radius:10px;padding:12px"><div style="font-weight:700;color:#1e293b;margin-bottom:4px">&#128100; Distribution</div><div style="font-size:12px;color:#64748b">Who gains and who loses? Aggregate welfare can rise while specific groups suffer.</div></div>\n')
w('<div style="background:#f1f5f9;border-radius:10px;padding:12px"><div style="font-weight:700;color:#1e293b;margin-bottom:4px">&#9878; Alternatives</div><div style="font-size:12px;color:#64748b">Compared to what? Every policy should be evaluated against the realistic alternative, not the ideal.</div></div>\n')
w('<div style="background:#f1f5f9;border-radius:10px;padding:12px"><div style="font-weight:700;color:#1e293b;margin-bottom:4px">&#128203; Implementation</div><div style="font-size:12px;color:#64748b">Does theory match practice? Many good ideas fail in execution due to political economy or information problems.</div></div>\n')
w('</div></div>\n')
w('<div class="sh">&#128683; Common Mistakes to Avoid</div>\n')
w('<div class="al">\n')
w('<li><span>&#10060;</span><strong>Taking the question at face value:</strong> "Should we tax carbon?" needs more than yes/no &mdash; what kind? At what level? With what revenue use?</li>\n')
w('<li><span>&#10060;</span><strong>Ignoring counterarguments:</strong> Dedicate 20-25% of essay to the strongest objections and your responses</li>\n')
w('<li><span>&#10060;</span><strong>Being too abstract:</strong> "Inequality is bad" &mdash; use specific data: "UK Gini rose from 0.25 to 0.34 between 1979 and 2019"</li>\n')
w('<li><span>&#10060;</span><strong>Moralising without analysis:</strong> Explain WHY something is wrong economically, not just that it feels unfair</li>\n')
w('<li><span>&#10060;</span><strong>Ignoring trade-offs:</strong> Every policy has costs &mdash; acknowledge them and explain why benefits outweigh them</li>\n')
w('</div>\n')
w('<div class="sh">&#127942; Key Takeaways</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn">1</div><div><div class="tipt">Questions repeat themes</div><div class="tipd">Government intervention, inequality, and technology appear almost every year. Master these themes and you can handle any question.</div></div></div>\n')
w('<div class="tip"><div class="tipn">2</div><div><div class="tipt">Question types are predictable</div><div class="tipd">Master the four types (policy, assumption challenge, systemic, distributional) and you have a framework for any question JLI throws at you.</div></div></div>\n')
w('<div class="tip"><div class="tipn">3</div><div><div class="tipt">Nuance wins every time</div><div class="tipd">Simple yes/no answers never win. Conditional answers with specific evidence always outperform confident but simplistic positions.</div></div></div>\n')
w('<div class="tip"><div class="tipn">4</div><div><div class="tipt">Original angles differentiate</div><div class="tipd">Find the perspective others won\'t have. Reject the binary. Reframe the question. This is what separates winners from runners-up.</div></div></div>\n')
w('</div>\n')
w('</div>\n')
f.close()
print("Part 14 done")