f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="mentorship" class="section">\n')
w('<div class="stitle">&#127891; Mentorship &amp; Support Organizations</div>\n')
w('<div class="ssub">Vetted programs to help you prepare &mdash; from free resources to premium coaching</div>\n')
w('<div class="sh">&#11088; Tier 1 &mdash; Essay Competition Specialists</div>\n')
w('<div class="readgrid">\n')
w('<div class="bk"><div class="bki" style="background:#dbeafe">&#127891;</div><div><div class="bkt"><a href="https://www.polygence.org/" target="_blank">Polygence</a></div><div class="bka">1-on-1 PhD mentorship &bull; Harvard, MIT, Oxford mentors</div><span class="bktag" style="background:#dbeafe;color:#1d4ed8">$$$ &bull; Book 4-6 wks ahead</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#ede9fe">&#127891;</div><div><div class="bkt"><a href="https://www.lumiere-education.com/" target="_blank">Lumiere Education</a></div><div class="bka">Research mentorship + essay coaching &bull; PhD supervisors</div><span class="bktag" style="background:#ede9fe;color:#5b21b6">$$$ &bull; Apply 4-8 wks ahead</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#d1fae5">&#127891;</div><div><div class="bkt"><a href="https://www.crimsoneducation.org/" target="_blank">Crimson Education</a></div><div class="bka">Essay coaching &bull; Ivy League/Oxbridge tutors &bull; Competition prep</div><span class="bktag" style="background:#d1fae5;color:#065f46">$$$$ &bull; 2-4 wks</span></div></div>\n')
w('</div>\n')
w('<div class="sh">&#127979; Tier 2 &mdash; Academic Enrichment</div>\n')
w('<div class="readgrid">\n')
w('<div class="bk"><div class="bki" style="background:#fef3c7">&#127979;</div><div><div class="bkt"><a href="https://www.johnlockeinstitute.com/" target="_blank">John Locke Institute (Direct)</a></div><div class="bka">Summer school Oxford &bull; Online economics courses &bull; Past winning essays</div><span class="bktag" style="background:#fef3c7;color:#92400e">$$$ &bull; Most relevant</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#fee2e2">&#127979;</div><div><div class="bkt"><a href="https://www.oxford-royale.com/" target="_blank">Oxford Royale Academy</a></div><div class="bka">Oxford/Cambridge summer programs &bull; Essay workshops &bull; Economics courses</div><span class="bktag" style="background:#fee2e2;color:#991b1b">$$$ &bull; 2-3 months ahead</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#e0f2fe">&#127979;</div><div><div class="bkt"><a href="https://www.immerse.education/" target="_blank">Cambridge Immerse</a></div><div class="bka">Cambridge-based economics courses &bull; Essay writing workshops</div><span class="bktag" style="background:#e0f2fe;color:#0369a1">$$$ &bull; Plan ahead</span></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128218; Tier 3 &mdash; Economics Community</div>\n')
w('<div class="readgrid">\n')
w('<div class="bk"><div class="bki" style="background:#d1fae5">&#128218;</div><div><div class="bkt"><a href="https://www.youngeconomistssociety.org/" target="_blank">Young Economists Society</a></div><div class="bka">Economics competitions &bull; Research mentorship &bull; Professor connections</div><span class="bktag" style="background:#d1fae5;color:#065f46">$ &bull; Flexible</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#ede9fe">&#128218;</div><div><div class="bkt"><a href="https://www.emerginginvestigators.org/" target="_blank">Journal of Emerging Investigators</a></div><div class="bka">Peer-reviewed journal for students &bull; Harvard grad mentors &bull; Free to submit</div><span class="bktag" style="background:#ede9fe;color:#5b21b6">Free</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#fef3c7">&#128218;</div><div><div class="bkt"><a href="https://www.tcr.org/" target="_blank">Concord Review</a></div><div class="bka">Exemplary high school essays &bull; Sets standard for academic writing</div><span class="bktag" style="background:#fef3c7;color:#92400e">~$40/yr</span></div></div>\n')
w('</div>\n')
w('<div class="sh">&#127881; Tier 4 &mdash; Free Resources (Start Today)</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn" style="background:#16a34a">Free</div><div><div class="tipt"><a href="https://mru.org/" target="_blank">Marginal Revolution University</a></div><div class="tipd">Free economics courses by Tyler Cowen &amp; Alex Tabarrok. Covers micro, macro, labour economics. Excellent for Q2 and Q3.</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#16a34a">Free</div><div><div class="tipt"><a href="https://www.khanacademy.org/economics-finance-domain" target="_blank">Khan Academy Economics</a></div><div class="tipd">Foundation micro and macroeconomics. Start here to build core knowledge quickly before diving into competition-level analysis.</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#16a34a">Free</div><div><div class="tipt"><a href="https://www.nber.org/papers" target="_blank">NBER Working Papers</a></div><div class="tipd">National Bureau of Economic Research. Latest academic economics research. Cite these for maximum credibility with judges.</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#16a34a">Free</div><div><div class="tipt"><a href="https://www.economicsnetwork.ac.uk/" target="_blank">Economics Network (UK)</a></div><div class="tipd">UK-focused resources for economics students. Essay writing guides. Directly relevant for JLI (Oxford-based competition).</div></div></div>\n')
w('</div>\n')
f.close()
print("Part 11 done")