f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div class="sh" style="color:#dc2626">&#128181; Topic 5: Debt &amp; Fiscal Sustainability</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn" style="background:#dc2626">Hawks</div><div><div class="tipt">Debt Hawks View</div><div class="tipd">High debt crowds out private investment &bull; Interest payments divert resources from public services &bull; Debt burdens future generations &bull; Inflation is the ultimate constraint</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#2563eb">Doves</div><div><div class="tipt">Debt Doves / MMT View</div><div class="tipd">Governments issuing own currency cannot default &bull; Debt is money spent but not taxed back &bull; Real resources, not money, are the constraint &bull; Austerity is self-defeating in recessions</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#059669">Thesis</div><div><div class="tipt">Winning Argument</div><div class="tipd">Not whether debt is "too high" in the abstract, but whether borrowing is used productively. Debt financing investment in infrastructure, education, and climate transition can pay for itself; debt financing consumption or tax cuts for the wealthy cannot. r &lt; g for most of history (Blanchard 2019).</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#7c3aed">Data</div><div><div class="tipt">Key Statistics</div><div class="tipd">US debt: 120% of GDP (2024) &bull; Japan debt: 260% of GDP, no crisis &bull; US interest payments: $1T/year &bull; Infrastructure investment multiplier: 1.5-2.0x (IMF)</div></div></div>\n')
w('</div>\n')
w('<div class="sh" style="color:#16a34a">&#127807; Topic 6: Food Security &amp; Agricultural Economics</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn" style="background:#16a34a">For</div><div><div class="tipt">Pro-Intervention</div><div class="tipd">Food security is a national security issue &bull; Agriculture has positive externalities (rural communities, landscape) &bull; Climate change requires transition support &bull; Small farmers cannot compete with agribusiness</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#dc2626">Against</div><div><div class="tipt">Pro-Market</div><div class="tipd">Agricultural subsidies distort trade and harm developing countries &bull; Subsidies flow to large agribusiness, not family farms &bull; Price signals should guide production &bull; Food is abundant; distribution is the problem</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#059669">Thesis</div><div><div class="tipt">Winning Argument</div><div class="tipd">Current subsidies are indefensible &mdash; they flow to wealthy landowners and encourage environmental damage. Solution: redirect support toward public goods: soil health, biodiversity, carbon sequestration, and food system resilience. Payment for ecosystem services, not commodity support.</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#7c3aed">Data</div><div><div class="tipt">Key Statistics</div><div class="tipd">US farm subsidies: $20B/year &bull; 80% of EU CAP goes to 20% of farms &bull; Agriculture: 10% of global emissions (IPCC) &bull; 3 companies control 60% of global seed market &bull; Food prices rose 30% (2021-2022)</div></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128218; Cross-Cutting Reading List</div>\n')
w('<div class="readgrid">\n')
w('<div class="bk"><div class="bki" style="background:#dbeafe">&#129302;</div><div><div class="bkt">Human Compatible</div><div class="bka">Stuart Russell &mdash; AI Governance</div><span class="bktag" style="background:#dbeafe;color:#1d4ed8">Topic 1</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#d1fae5">&#127968;</div><div><div class="bkt">Rethinking the Economics of Land and Housing</div><div class="bka">Ryan-Collins et al. &mdash; Housing</div><span class="bktag" style="background:#d1fae5;color:#065f46">Topic 2</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#fef3c7">&#127981;</div><div><div class="bkt">The Entrepreneurial State</div><div class="bka">Mariana Mazzucato &mdash; Industrial Policy</div><span class="bktag" style="background:#fef3c7;color:#92400e">Topic 3</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#ede9fe">&#128188;</div><div><div class="bkt">Cloud Empires</div><div class="bka">Vili Lehdonvirta &mdash; Gig Economy</div><span class="bktag" style="background:#ede9fe;color:#5b21b6">Topic 4</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#fee2e2">&#128181;</div><div><div class="bkt">The Deficit Myth</div><div class="bka">Stephanie Kelton &mdash; Fiscal Policy (+ critiques)</div><span class="bktag" style="background:#fee2e2;color:#991b1b">Topic 5</span></div></div>\n')
w('<div class="bk"><div class="bki" style="background:#d1fae5">&#127807;</div><div><div class="bkt">Stuffed and Starved</div><div class="bka">Raj Patel &mdash; Food Security</div><span class="bktag" style="background:#d1fae5;color:#065f46">Topic 6</span></div></div>\n')
w('</div>\n')
w('</div>\n')
f.close()
print("Part 17 done")