f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="scoring" class="section">\n')
w('<div class="stitle">&#127942; Scoring &amp; Judging Criteria</div>\n')
w('<div class="ssub">What JLI judges look for &mdash; based on past winner analysis</div>\n')
w('<div class="rg">\n')
w('<div class="ri"><div class="rpct">30%</div><div class="rname">Argument Quality</div><div class="rdesc">Clear thesis, logical structure, no fallacies, addresses counterarguments</div><div class="rbar"><div class="rfill"></div></div></div>\n')
w('<div class="ri"><div class="rpct">25%</div><div class="rname">Economic Analysis</div><div class="rdesc">Correct use of economic concepts, models, and frameworks</div><div class="rbar"><div class="rfill"></div></div></div>\n')
w('<div class="ri"><div class="rpct">20%</div><div class="rname">Evidence &amp; Data</div><div class="rdesc">Specific statistics, credible sources, real-world examples</div><div class="rbar"><div class="rfill"></div></div></div>\n')
w('<div class="ri"><div class="rpct">15%</div><div class="rname">Originality</div><div class="rdesc">Novel angle, unexpected insight, goes beyond obvious points</div><div class="rbar"><div class="rfill"></div></div></div>\n')
w('<div class="ri"><div class="rpct">10%</div><div class="rname">Writing Quality</div><div class="rdesc">Clear prose, precise language, appropriate academic register</div><div class="rbar"><div class="rfill"></div></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128161; What Separates Winners from Runners-Up</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn">1</div><div><div class="tipt">Take a clear, defensible position</div><div class="tipd">Judges reward intellectual courage. "It depends" is not a thesis. State your view and defend it rigorously.</div></div></div>\n')
w('<div class="tip"><div class="tipn">2</div><div><div class="tipt">Use economic concepts precisely</div><div class="tipd">Name the model. Say "monopsony" not "unfair wages." Say "deadweight loss" not "inefficiency." Precision signals mastery.</div></div></div>\n')
w('<div class="tip"><div class="tipn">3</div><div><div class="tipt">Engage the strongest counterargument</div><div class="tipd">Find the best argument against your thesis and address it directly. Ignoring it signals weakness.</div></div></div>\n')
w('<div class="tip"><div class="tipn">4</div><div><div class="tipt">Use specific data, not vague claims</div><div class="tipd">"Sweden has 98% digital transactions" beats "many countries are going cashless." Specificity = credibility.</div></div></div>\n')
w('<div class="tip"><div class="tipn">5</div><div><div class="tipt">Show institutional awareness</div><div class="tipd">The best essays consider how laws, regulations, and market structures shape outcomes. Pure theory without context loses marks.</div></div></div>\n')
w('<div class="tip"><div class="tipn">6</div><div><div class="tipt">Write for a smart non-specialist</div><div class="tipd">Explain concepts briefly but don\'t over-explain. Assume an intelligent reader who is not an economist.</div></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128683; Common Mistakes to Avoid</div>\n')
w('<div class="al">\n')
w('<li><span>&#10060;</span><strong>Descriptive not analytical:</strong> Describing what Amazon does instead of analysing whether it constitutes exploitation</li>\n')
w('<li><span>&#10060;</span><strong>Weak thesis:</strong> "There are arguments on both sides" &mdash; this is not a thesis, it is an observation</li>\n')
w('<li><span>&#10060;</span><strong>Missing counterarguments:</strong> Only presenting one side makes the essay look like advocacy, not analysis</li>\n')
w('<li><span>&#10060;</span><strong>Vague evidence:</strong> "Studies show..." without citing which studies or what they found</li>\n')
w('<li><span>&#10060;</span><strong>Over-long introduction:</strong> Judges want your argument quickly. Get to your thesis by paragraph 1.</li>\n')
w('<li><span>&#10060;</span><strong>Ignoring the question:</strong> Answering a related but different question. Re-read the question before every paragraph.</li>\n')
w('</div>\n</div>\n')
f.close()
print("Part 8 done")