f = open("outputs/john-locke-essay/john-locke-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="econres" class="section">\n')
w('<div class="stitle">&#128202; Economics Research Guide</div>\n')
w('<div class="ssub">Competition overview, research topics, and essay strategy for JLI 2026</div>\n')
w('<div class="sh">&#127919; What Judges Look For</div>\n')
w('<div class="sg" style="grid-template-columns:repeat(auto-fit,minmax(160px,1fr))">\n')
w('<div class="sc"><div class="si">&#128161;</div><div class="sl">Original thinking &mdash; not textbook answers</div></div>\n')
w('<div class="sc"><div class="si">&#128203;</div><div class="sl">Clear argumentation with logical structure</div></div>\n')
w('<div class="sc"><div class="si">&#9878;</div><div class="sl">Engagement with counterarguments</div></div>\n')
w('<div class="sc"><div class="si">&#128202;</div><div class="sl">Evidence-based reasoning with data</div></div>\n')
w('<div class="sc"><div class="si">&#9997;</div><div class="sl">Clear, concise, sophisticated prose</div></div>\n')
w('</div>\n')
w('<div class="sh">&#128218; Core Economics Themes (Historical)</div>\n')
w('<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px;margin-bottom:18px">\n')
w('<div class="card"><div class="ctitle">Market Mechanisms</div><div class="al"><li>Market failures and government intervention</li><li>Price mechanisms and resource allocation</li><li>Externalities and public goods</li></div></div>\n')
w('<div class="card"><div class="ctitle">Inequality &amp; Distribution</div><div class="al"><li>Wealth and income inequality</li><li>Redistribution policies</li><li>Intergenerational mobility</li></div></div>\n')
w('<div class="card"><div class="ctitle">Monetary &amp; Fiscal Policy</div><div class="al"><li>Central bank independence</li><li>Inflation targeting</li><li>Government debt and deficits</li></div></div>\n')
w('<div class="card"><div class="ctitle">International Economics</div><div class="al"><li>Trade policy and protectionism</li><li>Globalisation effects</li><li>Currency and exchange rates</li></div></div>\n')
w('<div class="card"><div class="ctitle">Behavioural Economics</div><div class="al"><li>Rationality assumptions</li><li>Nudge theory and paternalism</li><li>Decision-making biases</li></div></div>\n')
w('<div class="card"><div class="ctitle">Environmental Economics</div><div class="al"><li>Carbon pricing mechanisms</li><li>Sustainability and growth</li><li>Climate change economics</li></div></div>\n')
w('</div>\n')
w('<div class="sh">&#128300; Research Topics to Explore</div>\n')
w('<div class="tipgrid">\n')
w('<div class="tip"><div class="tipn" style="background:#2563eb">1</div><div><div class="tipt">Economics of Artificial Intelligence</div><div class="tipd">Will AI increase or decrease inequality? &bull; How should governments respond to AI-driven job displacement? &bull; Key: Acemoglu &amp; Restrepo (2019), Brynjolfsson &amp; McAfee, OECD AI reports</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#7c3aed">2</div><div><div class="tipt">Universal Basic Income (UBI)</div><div class="tipd">Is UBI economically feasible? &bull; What are the labour supply effects? &bull; Key: Finland UBI experiment, GiveDirectly Kenya, Milton Friedman negative income tax</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#059669">3</div><div><div class="tipt">Central Bank Digital Currencies (CBDCs)</div><div class="tipd">Should central banks issue digital currencies? &bull; Privacy implications? &bull; Key: BIS CBDC reports, China digital yuan pilot, ECB digital euro project</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#d97706">4</div><div><div class="tipt">Carbon Pricing &amp; Climate Economics</div><div class="tipd">Carbon tax vs. cap-and-trade? &bull; Can growth decouple from emissions? &bull; Key: Nordhaus Nobel Prize work, EU ETS data, Carbon Border Adjustment Mechanism</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#dc2626">5</div><div><div class="tipt">Economics of Healthcare</div><div class="tipd">Is healthcare a public good? &bull; How to incentivise pharmaceutical innovation? &bull; Key: Arrow (1963) "Uncertainty and Welfare Economics of Medical Care", OECD Health Statistics</div></div></div>\n')
w('<div class="tip"><div class="tipn" style="background:#16a34a">6</div><div><div class="tipt">Degrowth vs. Green Growth</div><div class="tipd">Is perpetual economic growth possible or desirable? &bull; Can technology solve environmental limits? &bull; Key: Kate Raworth "Doughnut Economics", Tim Jackson "Prosperity Without Growth"</div></div></div>\n')
w('</div>\n')
f.close()
print("Part 18 done")