f = open("outputs/cambridge-essay/cambridge-essay-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div class="footer">&#127891; Cambridge Re:think Essay Competition 2026 &mdash; Senior Division Visual Guide &bull; <a href="https://cambridge-research.org/essay-competition/" target="_blank">cambridge-research.org</a></div>\n')
w('<script>\n')
w('function show(id){\n')
w('  document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));\n')
w('  document.querySelectorAll(".nav-tab").forEach(t=>t.classList.remove("active"));\n')
w('  var el=document.getElementById(id);\n')
w('  if(el)el.classList.add("active");\n')
w('  var map={overview:0,prompts:1,strategy:2,structure:3,reading:4,timeline:5,checklist:6};\n')
w('  var tabs=document.querySelectorAll(".nav-tab");\n')
w('  if(map[id]!==undefined&&tabs[map[id]])tabs[map[id]].classList.add("active");\n')
w('}\n')
w('function toggle(id){\n')
w('  var el=document.getElementById(id);\n')
w('  if(el)el.classList.toggle("open");\n')
w('}\n')
w('(function(){\n')
w('  var dates=[new Date("2026-05-10"),new Date("2026-05-26"),new Date("2026-07-31")];\n')
w('  var ids=["d1","d2","d3"];\n')
w('  var now=new Date();\n')
w('  dates.forEach(function(d,i){\n')
w('    var diff=Math.ceil((d-now)/86400000);\n')
w('    var el=document.getElementById(ids[i]);\n')
w('    if(el)el.textContent=diff>0?diff:"PASSED";\n')
w('  });\n')
w('})();\n')
w('</script>\n')
w('</body>\n</html>\n')
f.close()
print("Part 10 done")