f = open("outputs/cambridge-essay/cambridge-essay-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div class="hero">\n')
w('<h1>&#127891; Cambridge Re:think Essay Competition 2026</h1>\n')
w('<div class="sub">Senior Division (Ages 14&ndash;18) &bull; Visual Study Guide &bull; 9 Prompts from Harvard, Stanford, Oxford &amp; Cambridge Professors</div>\n')
w('<div class="badges">\n')
w('<span class="badge">&#127381; FREE Entry</span>\n')
w('<span class="badge">&#128196; Max 2,000 Words</span>\n')
w('<span class="badge">&#127942; $150 Gold + Cambridge Ceremony</span>\n')
w('<span class="badge">&#127758; Open Worldwide</span>\n')
w('<span class="badge">&#128683; No AI Assistance</span>\n')
w('</div>\n')
w('<div class="countdown-row">\n')
w('<div class="cd-box"><span class="num" id="d1">--</span><span class="lbl">Days to Deadline</span></div>\n')
w('<div class="cd-box"><span class="num" id="d2">--</span><span class="lbl">Days to Results</span></div>\n')
w('<div class="cd-box"><span class="num" id="d3">--</span><span class="lbl">Days to Cambridge</span></div>\n')
w('</div>\n</div>\n')
w('<nav>\n')
w('<button class="nav-tab active" onclick="show(\'overview\')">&#127968; Overview</button>\n')
w('<button class="nav-tab" onclick="show(\'prompts\')">&#10067; All 9 Prompts</button>\n')
w('<button class="nav-tab" onclick="show(\'strategy\')">&#127919; Strategy</button>\n')
w('<button class="nav-tab" onclick="show(\'structure\')">&#128196; Essay Structure</button>\n')
w('<button class="nav-tab" onclick="show(\'reading\')">&#128218; Reading Lists</button>\n')
w('<button class="nav-tab" onclick="show(\'timeline\')">&#128197; Timeline</button>\n')
w('<button class="nav-tab" onclick="show(\'checklist\')">&#9989; Checklist</button>\n')
w('</nav>\n')
f.close()
print("Part 2 done")