f = open("outputs/cambridge-essay/cambridge-essay-visual-guide.html", "a", encoding="utf-8")
w = f.write
w('<div id="checklist" class="section">\n')
w('<div class="sh">&#9989; Final Submission Checklist</div>\n')
w('<div class="warn">&#128683; The competition uses both a plagiarism checker AND an AI checker. Any AI-assisted writing will be detected and disqualified.</div>\n')
w('<div class="grid2">\n')
w('<div class="card"><div class="ctitle">&#128196; Before You Write</div>\n')
w('<ul class="al">\n')
w('<li><span>&#9744;</span>Chosen ONE prompt only</li>\n')
w('<li><span>&#9744;</span>Read at least 3 books from the professor reading list</li>\n')
w('<li><span>&#9744;</span>Written a clear, arguable thesis statement</li>\n')
w('<li><span>&#9744;</span>Outlined your 3 body paragraphs</li>\n')
w('<li><span>&#9744;</span>Identified the strongest counterargument to address</li>\n')
w('</ul></div>\n')
w('<div class="card"><div class="ctitle">&#9997;&#65039; While Writing</div>\n')
w('<ul class="al">\n')
w('<li><span>&#9744;</span>Every claim is supported by an academic source</li>\n')
w('<li><span>&#9744;</span>Counterargument is addressed fairly and rebutted</li>\n')
w('<li><span>&#9744;</span>Introduction has a hook, context, and clear thesis</li>\n')
w('<li><span>&#9744;</span>Conclusion goes beyond summary to broader implication</li>\n')
w('<li><span>&#9744;</span>Writing is entirely your own (no AI assistance)</li>\n')
w('</ul></div>\n')
w('<div class="card"><div class="ctitle">&#128196; Before Submission</div>\n')
w('<ul class="al">\n')
w('<li><span>&#9744;</span>Word count is 2,000 or fewer (excluding footnotes &amp; bibliography)</li>\n')
w('<li><span>&#9744;</span>All citations are in MLA 8 format</li>\n')
w('<li><span>&#9744;</span>Essay is in PDF format</li>\n')
w('<li><span>&#9744;</span><strong>Name, school, and personal info REMOVED from PDF</strong></li>\n')
w('<li><span>&#9744;</span>Referee email address ready (teacher or counsellor)</li>\n')
w('<li><span>&#9744;</span>Submitted via CCIR portal before deadline</li>\n')
w('</ul></div>\n')
w('<div class="card"><div class="ctitle">&#128683; Never Do This</div>\n')
w('<ul class="al">\n')
w('<li><span style="background:#ef4444">!</span>Use AI to write, paraphrase, or edit any part of the essay</li>\n')
w('<li><span style="background:#ef4444">!</span>Copy text from any source without citation</li>\n')
w('<li><span style="background:#ef4444">!</span>Ask someone else to write or co-write the essay</li>\n')
w('<li><span style="background:#ef4444">!</span>Submit more than one essay</li>\n')
w('<li><span style="background:#ef4444">!</span>Leave your name in the PDF document</li>\n')
w('</ul></div>\n')
w('</div>\n')
w('<div class="sh">&#127942; Competition at King\'s College, Cambridge</div>\n')
w('<div class="card">\n')
w('<p style="color:#475569;font-size:14px;margin-bottom:12px">Award winners are invited to the <strong>Award Ceremony &amp; Dinner at King\'s College, Cambridge</strong> on <strong>31 July 2026</strong>. The dinner is held in the Hall designed by William Wilkins in the 1820s &mdash; one of the most magnificent halls of its era. Attendees also receive complimentary access to King\'s College Chapel, construction of which began in 1446 under Henry VI.</p>\n')
w('<p style="color:#475569;font-size:14px">The 2026 ceremony will feature a keynote by <strong>Dr Barry C. Barish</strong>, Nobel Prize Laureate in Physics 2017, for his contributions to the LIGO detector and the observation of gravitational waves.</p>\n')
w('</div>\n')
w('</div>\n')
f.close()
print("Part 9 done")