import os
os.makedirs("outputs/cambridge-essay", exist_ok=True)
f = open("outputs/cambridge-essay/cambridge-essay-visual-guide.html", "w", encoding="utf-8")
w = f.write
w('<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n')
w('<meta name="viewport" content="width=device-width, initial-scale=1.0">\n')
w('<title>Cambridge Re:think Essay Competition 2026 &mdash; Student Visual Guide</title>\n')
w('<style>\n')
w('*{box-sizing:border-box;margin:0;padding:0}\n')
w('body{font-family:"Segoe UI",Arial,sans-serif;background:#f0f4f8;color:#1e293b;line-height:1.6}\n')
w('.hero{background:linear-gradient(135deg,#1e3a5f 0%,#2563eb 60%,#7c3aed 100%);color:#fff;padding:40px 24px 32px;text-align:center}\n')
w('.hero h1{font-size:clamp(22px,4vw,36px);font-weight:800;letter-spacing:-0.5px;margin-bottom:8px}\n')
w('.hero .sub{font-size:15px;opacity:0.88;margin-bottom:20px}\n')
w('.badges{display:flex;flex-wrap:wrap;gap:10px;justify-content:center;margin-bottom:20px}\n')
w('.badge{background:rgba(255,255,255,0.18);border:1px solid rgba(255,255,255,0.35);border-radius:20px;padding:5px 14px;font-size:13px;font-weight:600}\n')
w('.countdown-row{display:flex;gap:16px;justify-content:center;flex-wrap:wrap}\n')
w('.cd-box{background:rgba(255,255,255,0.15);border-radius:10px;padding:12px 20px;text-align:center;min-width:80px}\n')
w('.cd-box .num{font-size:28px;font-weight:800;display:block}\n')
w('.cd-box .lbl{font-size:11px;opacity:0.8;text-transform:uppercase;letter-spacing:1px}\n')
w('nav{background:#1e293b;display:flex;flex-wrap:wrap;gap:2px;padding:8px 12px;position:sticky;top:0;z-index:100}\n')
w('.nav-tab{background:transparent;border:none;color:#94a3b8;padding:7px 14px;border-radius:6px;cursor:pointer;font-size:13px;font-weight:500;transition:all 0.2s}\n')
w('.nav-tab:hover,.nav-tab.active{background:#2563eb;color:#fff}\n')
w('.section{display:none;max-width:960px;margin:0 auto;padding:24px 16px}\n')
w('.section.active{display:block}\n')
w('.sh{font-size:18px;font-weight:700;color:#1e3a5f;border-left:4px solid #2563eb;padding-left:12px;margin:24px 0 14px}\n')
w('.card{background:#fff;border-radius:12px;padding:18px 20px;margin-bottom:14px;box-shadow:0 2px 8px rgba(0,0,0,0.07)}\n')
w('.ctitle{font-weight:700;font-size:15px;color:#1e3a5f;margin-bottom:8px}\n')
w('.grid2{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px;margin-bottom:14px}\n')
w('.grid3{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin-bottom:14px}\n')
w('.stat-box{background:#fff;border-radius:10px;padding:16px;text-align:center;box-shadow:0 2px 8px rgba(0,0,0,0.07)}\n')
w('.stat-num{font-size:28px;font-weight:800;color:#2563eb;display:block}\n')
w('.stat-lbl{font-size:12px;color:#64748b;margin-top:4px}\n')
w('.prompt-card{background:#fff;border-radius:12px;padding:18px 20px;margin-bottom:12px;box-shadow:0 2px 8px rgba(0,0,0,0.07);border-left:4px solid #2563eb;cursor:pointer;transition:all 0.2s}\n')
w('.prompt-card:hover{transform:translateY(-2px);box-shadow:0 4px 16px rgba(37,99,235,0.15)}\n')
w('.p1{border-left-color:#ef4444!important}.p2{border-left-color:#f97316!important}.p3{border-left-color:#8b5cf6!important}\n')
w('.p4{border-left-color:#10b981!important}.p5{border-left-color:#f59e0b!important}.p6{border-left-color:#06b6d4!important}\n')
w('.p7{border-left-color:#ec4899!important}.p8{border-left-color:#14b8a6!important}.p9{border-left-color:#6366f1!important}\n')
w('.prompt-num{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#64748b;margin-bottom:4px}\n')
w('.prompt-q{font-size:15px;font-weight:700;color:#1e293b;margin-bottom:8px}\n')
w('.prompt-meta{display:flex;gap:8px;flex-wrap:wrap}\n')
w('.tag{background:#f1f5f9;border-radius:12px;padding:3px 10px;font-size:12px;color:#475569;font-weight:500}\n')
w('.tag.hot{background:#fef2f2;color:#dc2626}.tag.orig{background:#f0fdf4;color:#16a34a}.tag.hard{background:#faf5ff;color:#7c3aed}\n')
w('.detail-box{background:#f8fafc;border-radius:8px;padding:14px;margin-top:10px;display:none;font-size:14px}\n')
w('.detail-box.open{display:block}\n')
w('.al{list-style:none;padding:0}\n')
w('.al li{display:flex;gap:10px;padding:8px 0;border-bottom:1px solid #f1f5f9;font-size:14px;align-items:flex-start}\n')
w('.al li:last-child{border-bottom:none}\n')
w('.al li span{background:#2563eb;color:#fff;border-radius:50%;width:22px;height:22px;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700;flex-shrink:0;margin-top:1px}\n')
w('.prize-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;margin-bottom:14px}\n')
w('.prize-box{border-radius:10px;padding:14px;text-align:center}\n')
w('.prize-box.gold{background:linear-gradient(135deg,#fef3c7,#fde68a);border:2px solid #f59e0b}\n')
w('.prize-box.silver{background:linear-gradient(135deg,#f1f5f9,#e2e8f0);border:2px solid #94a3b8}\n')
w('.prize-box.bronze{background:linear-gradient(135deg,#fef3c7,#fed7aa);border:2px solid #d97706}\n')
w('.prize-box.special{background:linear-gradient(135deg,#ede9fe,#ddd6fe);border:2px solid #7c3aed}\n')
w('.prize-box .pname{font-weight:700;font-size:14px;margin-bottom:4px}\n')
w('.prize-box .pamount{font-size:20px;font-weight:800;color:#1e293b}\n')
w('.prize-box .pdesc{font-size:11px;color:#64748b;margin-top:4px}\n')
w('.timeline{position:relative;padding-left:28px}\n')
w('.timeline::before{content:"";position:absolute;left:8px;top:0;bottom:0;width:2px;background:#e2e8f0}\n')
w('.tl-item{position:relative;margin-bottom:16px}\n')
w('.tl-item::before{content:"";position:absolute;left:-24px;top:4px;width:12px;height:12px;border-radius:50%;background:#2563eb;border:2px solid #fff;box-shadow:0 0 0 2px #2563eb}\n')
w('.tl-item.done::before{background:#10b981;box-shadow:0 0 0 2px #10b981}\n')
w('.tl-item.urgent::before{background:#ef4444;box-shadow:0 0 0 2px #ef4444}\n')
w('.tl-date{font-size:12px;font-weight:700;color:#2563eb;text-transform:uppercase;letter-spacing:0.5px}\n')
w('.tl-title{font-weight:600;font-size:14px;color:#1e293b}\n')
w('.tl-desc{font-size:13px;color:#64748b;margin-top:2px}\n')
w('.thesis-box{background:linear-gradient(135deg,#eff6ff,#dbeafe);border:1px solid #bfdbfe;border-radius:10px;padding:16px;margin-bottom:12px}\n')
w('.thesis-label{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#2563eb;margin-bottom:6px}\n')
w('.thesis-text{font-size:14px;font-style:italic;color:#1e3a5f;line-height:1.6}\n')
w('.book-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px}\n')
w('.book-card{background:#fff;border-radius:8px;padding:12px;box-shadow:0 1px 4px rgba(0,0,0,0.08);border-top:3px solid #2563eb}\n')
w('.book-title{font-weight:700;font-size:13px;color:#1e293b;margin-bottom:3px}\n')
w('.book-author{font-size:12px;color:#64748b;margin-bottom:4px}\n')
w('.book-why{font-size:12px;color:#475569;font-style:italic}\n')
w('.warn{background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:12px 14px;margin-bottom:10px;font-size:13px;color:#dc2626}\n')
w('.tip{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:12px 14px;margin-bottom:10px;font-size:13px;color:#15803d}\n')
w('.footer{background:#1e293b;color:#94a3b8;text-align:center;padding:20px;font-size:13px;margin-top:24px}\n')
w('.footer a{color:#60a5fa;text-decoration:none}\n')
w('table{width:100%;border-collapse:collapse;font-size:13px}\n')
w('th{background:#1e293b;color:#fff;padding:10px;text-align:left}\n')
w('td{padding:9px 10px;border-bottom:1px solid #f1f5f9}\n')
w('tr:nth-child(even){background:#f8fafc}\n')
w('</style>\n</head>\n<body>\n')
f.close()
print("Part 1 done")