f = open("outputs/cambridge-essay/cambridge-essay-visual-guide.html", "a", encoding="utf-8")
w = f.write
# OVERVIEW SECTION
w('<div id="overview" class="section active">\n')
w('<div class="sh">&#127881; Competition at a Glance</div>\n')
w('<div class="grid3">\n')
w('<div class="stat-box"><span class="stat-num">9</span><div class="stat-lbl">Essay Prompts to Choose From</div></div>\n')
w('<div class="stat-box"><span class="stat-num">2,000</span><div class="stat-lbl">Max Word Count</div></div>\n')
w('<div class="stat-box"><span class="stat-num">13,000+</span><div class="stat-lbl">Submissions in 2025</div></div>\n')
w('<div class="stat-box"><span class="stat-num">50+</span><div class="stat-lbl">Countries Represented</div></div>\n')
w('<div class="stat-box"><span class="stat-num">FREE</span><div class="stat-lbl">Entry Fee</div></div>\n')
w('<div class="stat-box"><span class="stat-num">Top 10%</span><div class="stat-lbl">Receive Honourable Mention</div></div>\n')
w('</div>\n')
w('<div class="sh">&#127942; Prizes &mdash; Senior Division</div>\n')
w('<div class="prize-row">\n')
w('<div class="prize-box gold"><div class="pname">&#129351; Gold</div><div class="pamount">$150</div><div class="pdesc">10 recipients &bull; $500 scholarship &bull; Cambridge ceremony</div></div>\n')
w('<div class="prize-box silver"><div class="pname">&#129352; Silver</div><div class="pamount">$100</div><div class="pdesc">10 recipients &bull; $300 scholarship &bull; Cambridge ceremony</div></div>\n')
w('<div class="prize-box bronze"><div class="pname">&#129353; Bronze</div><div class="pamount">$50</div><div class="pdesc">10 recipients &bull; $200 scholarship &bull; Cambridge ceremony</div></div>\n')
w('<div class="prize-box special"><div class="pname">&#128221; Logos Prize</div><div class="pamount">$150</div><div class="pdesc">Best Argument &bull; 1 global recipient</div></div>\n')
w('<div class="prize-box special"><div class="pname">&#9997;&#65039; Pathos Prize</div><div class="pamount">$150</div><div class="pdesc">Best Writing &bull; 1 global recipient</div></div>\n')
w('<div class="prize-box special"><div class="pname">&#128270; Ethos Prize</div><div class="pamount">$150</div><div class="pdesc">Best Research &bull; 1 global recipient</div></div>\n')
w('</div>\n')
w('<div class="tip">&#127891; All prize winners are invited to the Award Ceremony &amp; Dinner at <strong>King\'s College, Cambridge</strong> on 31 July 2026 &mdash; free of charge for Gold/Silver/Bronze/Special prize recipients.</div>\n')
w('<div class="sh">&#128203; Key Rules</div>\n')
w('<div class="grid2">\n')
w('<div class="card"><div class="ctitle">&#128196; Submission Requirements</div>\n')
w('<ul class="al">\n')
w('<li><span>1</span>Max 2,000 words (footnotes &amp; bibliography excluded)</li>\n')
w('<li><span>2</span>PDF format only</li>\n')
w('<li><span>3</span>MLA 8 citation format</li>\n')
w('<li><span>4</span>Remove your name from the PDF (blind review)</li>\n')
w('<li><span>5</span>Submit via CCIR portal</li>\n')
w('<li><span>6</span>Provide referee email (teacher/counsellor)</li>\n')
w('</ul></div>\n')
w('<div class="card"><div class="ctitle">&#128683; Disqualification Triggers</div>\n')
w('<ul class="al">\n')
w('<li><span style="background:#ef4444">!</span>Any use of AI writing assistance</li>\n')
w('<li><span style="background:#ef4444">!</span>Plagiarism in any form</li>\n')
w('<li><span style="background:#ef4444">!</span>Co-authorship (must be sole author)</li>\n')
w('<li><span style="background:#ef4444">!</span>Submitting more than one essay</li>\n')
w('<li><span style="background:#ef4444">!</span>Addressing more than one prompt</li>\n')
w('<li><span style="background:#ef4444">!</span>Name/school left in PDF document</li>\n')
w('</ul></div>\n')
w('</div>\n')
w('<div class="sh">&#127775; What Judges Look For</div>\n')
w('<div class="card">\n')
w('<table>\n')
w('<tr><th>Criterion</th><th>What It Means</th><th>How to Excel</th></tr>\n')
w('<tr><td><strong>Original Ideas</strong></td><td>Genuine intellectual contribution</td><td>Don\'t just summarise — take a clear, arguable position</td></tr>\n')
w('<tr><td><strong>Quality of Argument</strong></td><td>Clear structure, evidence-backed claims</td><td>Every claim needs a source; address counterarguments</td></tr>\n')
w('<tr><td><strong>Quality of Writing</strong></td><td>Language, flow, engagement</td><td>Vary sentence length; use precise vocabulary</td></tr>\n')
w('<tr><td><strong>Research Depth</strong></td><td>Academic sources, proper citations</td><td>Use books from the professor reading lists; cite correctly in MLA 8</td></tr>\n')
w('</table>\n')
w('</div>\n')
w('</div>\n')
f.close()
print("Part 3 done")